# Generated by Django 3.0.4 on 2020-03-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etu',
            name='kuva',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hanke',
            name='tavoite',
            field=models.TextField(blank=True),
        ),
    ]
